"""Reads/writes the real `.env` file using the parsed `.env.example`
schema as its layout.

Every save regenerates the whole file from the schema — section headers,
help comments, then `KEY=value` — rather than patching individual lines.
That's simpler than a line-level diff, and it means `.env` always mirrors
`.env.example`'s shape, comments included, no matter how it got out of
sync before. Keys present in the current `.env` but missing from the
schema (hand-added ones, or leftovers from an older `.env.example`) are
kept and appended under a trailing "Custom" section instead of being
silently dropped.
"""

from __future__ import annotations

from pathlib import Path

from . import env_schema


def read_current(env_path: Path) -> dict[str, str]:
    """Parse the existing `.env` into a flat key -> value dict.

    Deliberately tolerant: blank lines, comments, and anything without an
    `=` are skipped rather than raising, since a hand-edited `.env` in the
    wild is exactly the kind of file this needs to survive reading.
    """
    if not env_path.exists():
        return {}
    values: dict[str, str] = {}
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = val.strip()
    return values


def render(sections: list[env_schema.Section], values: dict[str, str]) -> str:
    known_keys = {f.key for f in env_schema.all_fields(sections)}
    lines = [
        "# =========================================================================",
        "# Generated by the MentahanPOV dashboard (python dashboard.py -> Config tab).",
        "# Hand edits survive the next save, but the dashboard is the source of truth.",
        "# =========================================================================",
        "",
    ]
    for section in sections:
        lines.append(f"# ---- {section.title} ----")
        for f in section.fields:
            if f.comment:
                lines.append(f"# {f.comment}")
            lines.append(f"{f.key}={values.get(f.key, f.default)}")
        lines.append("")

    extra = {k: v for k, v in values.items() if k not in known_keys}
    if extra:
        lines.append("# ---- Custom (not in .env.example) ----")
        for k, v in extra.items():
            lines.append(f"{k}={v}")
        lines.append("")

    return "\n".join(lines)


def write(
    env_path: Path, sections: list[env_schema.Section], values: dict[str, str]
) -> None:
    """Back up the current `.env` (one rolling `.env.bak`), then overwrite it."""
    if env_path.exists():
        backup = env_path.with_name(env_path.name + ".bak")
        backup.write_text(env_path.read_text(encoding="utf-8"), encoding="utf-8")
    env_path.write_text(render(sections, values), encoding="utf-8")
